basePath: /api
definitions:
  structs.Customer:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      user_id:
        type: integer
    type: object
  structs.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  structs.MenuItem:
    properties:
      category:
        type: string
      id:
        type: integer
      is_available:
        type: boolean
      name:
        type: string
      price:
        type: number
    type: object
  structs.Reservation:
    properties:
      created_at:
        type: string
      customer_id:
        type: integer
      id:
        type: integer
      number_of_guests:
        type: integer
      reservation_datetime:
        type: string
      status:
        type: string
      table_id:
        type: integer
    type: object
  structs.Table:
    properties:
      capacity:
        type: integer
      id:
        type: integer
      status:
        type: string
      table_number:
        type: string
    type: object
  structs.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      name:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
host: sancai-reservation-system-production.up.railway.app
info:
  contact: {}
  description: API restoran
  title: Sancai API
  version: "1.0"
paths:
  /customers:
    get:
      description: Mengambil data lengkap semua customer yang terdaftar
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.Customer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Ambil semua customer
      tags:
      - Customer
    post:
      consumes:
      - application/json
      description: Mendaftarkan customer baru dengan validasi email dan nomor telepon
        unik
      parameters:
      - description: Data Customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/structs.Customer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/structs.Customer'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Tambah customer
      tags:
      - Customer
  /customers/{id}:
    delete:
      description: Menghapus data customer secara permanen dari database
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Hapus customer
      tags:
      - Customer
    get:
      description: Mengambil data detail satu customer menggunakan parameter ID
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Customer'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Ambil customer berdasarkan ID
      tags:
      - Customer
    put:
      consumes:
      - application/json
      description: Mengubah nama, email, atau telepon customer berdasarkan ID
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Data Customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/structs.Customer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update data customer
      tags:
      - Customer
  /customers/{id}/reservations:
    get:
      description: Mengambil semua daftar reservasi yang pernah dibuat oleh customer
        tertentu
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.Reservation'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Riwayat reservasi customer
      tags:
      - Customer
  /login:
    post:
      consumes:
      - application/json
      description: Login pakai email dan password
      parameters:
      - description: Login input
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/structs.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Login user
      tags:
      - User
  /menu:
    get:
      description: Mengambil daftar lengkap item menu makanan dan minuman
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.MenuItem'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Ambil semua menu
      tags:
      - MenuItem
    post:
      consumes:
      - application/json
      description: Menambahkan item menu baru ke dalam sistem (Admin Only)
      parameters:
      - description: Data Menu Item
        in: body
        name: menu
        required: true
        schema:
          $ref: '#/definitions/structs.MenuItem'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/structs.MenuItem'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Tambah menu baru
      tags:
      - MenuItem
  /menu/{id}:
    delete:
      description: Menghapus item menu dari database berdasarkan ID
      parameters:
      - description: Menu Item ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Hapus menu
      tags:
      - MenuItem
    get:
      description: Mengambil data detail satu item menu menggunakan parameter ID
      parameters:
      - description: Menu Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.MenuItem'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Ambil menu berdasarkan ID
      tags:
      - MenuItem
    put:
      consumes:
      - application/json
      description: Mengubah nama, harga, atau status ketersediaan menu
      parameters:
      - description: Menu Item ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Data Menu
        in: body
        name: menu
        required: true
        schema:
          $ref: '#/definitions/structs.MenuItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update data menu
      tags:
      - MenuItem
  /menu/{id}/availability:
    patch:
      consumes:
      - application/json
      description: Mengubah status ketersediaan (available true/false) secara cepat
      parameters:
      - description: Menu Item ID
        in: path
        name: id
        required: true
        type: integer
      - description: Cukup isi field is_available
        in: body
        name: availability
        required: true
        schema:
          $ref: '#/definitions/structs.MenuItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update ketersediaan menu
      tags:
      - MenuItem
  /register:
    post:
      consumes:
      - application/json
      description: Mendaftarkan user baru ke sistem dengan name, email, password,
        dan role
      parameters:
      - description: Data User Baru
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/structs.User'
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "user registered"}'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: '{"error": "Invalid email format / Email already exists"}'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: '{"error": "could not create user"}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register user
      tags:
      - User
  /tables:
    get:
      description: Mengambil daftar lengkap meja beserta statusnya
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.Table'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Ambil semua meja
      tags:
      - Table
    post:
      consumes:
      - application/json
      description: Menambahkan meja ke sistem (Admin Only)
      parameters:
      - description: Data Meja
        in: body
        name: table
        required: true
        schema:
          $ref: '#/definitions/structs.Table'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/structs.Table'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Tambah meja baru
      tags:
      - Table
  /tables/{id}:
    delete:
      description: Menghapus meja jika tidak ada reservasi aktif di masa depan
      parameters:
      - description: Table ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Hapus meja
      tags:
      - Table
    get:
      description: Mengambil data detail satu meja menggunakan parameter ID
      parameters:
      - description: Table ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Table'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Ambil meja berdasarkan ID
      tags:
      - Table
    put:
      consumes:
      - application/json
      description: Mengubah nomor meja, kapasitas, atau status
      parameters:
      - description: Table ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Data Meja
        in: body
        name: table
        required: true
        schema:
          $ref: '#/definitions/structs.Table'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update info meja
      tags:
      - Table
  /tables/{id}/status:
    patch:
      consumes:
      - application/json
      description: Mengubah status (available/reserved/occupied) secara spesifik
      parameters:
      - description: Table ID
        in: path
        name: id
        required: true
        type: integer
      - description: Status Baru (Cukup isi field status)
        in: body
        name: status
        required: true
        schema:
          $ref: '#/definitions/structs.Table'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update status meja
      tags:
      - Table
  /tables/available:
    get:
      description: Mencari meja berdasarkan jumlah tamu dan waktu tertentu yang tidak
        bentrok dengan reservasi lain
      parameters:
      - description: 'Format: YYYY-MM-DD HH:MM:SS'
        example: '"2026-02-20 19:00:00"'
        in: query
        name: datetime
        required: true
        type: string
      - description: Jumlah tamu
        example: 4
        in: query
        name: guests
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.Table'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Cari meja tersedia
      tags:
      - Table
securityDefinitions:
  BearerAuth:
    description: 'Ketik: "Bearer [spasi] token_anda"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
